logger:
  level: "all"
  stdout: true
  path: "./logs/"
  file: "{Y-m-d}.log"

aliyun:
  cdnAccessKeyId: "cdn的access_id"
  cdnAccessKeySecret: "cdn的access_key"
  certAccessKeyId: "证书管理的access_id"
  certAccessKeySecret: "证书管理的access_key"
